version: '3'

services:

  main:
    image: josoder/jenkins:latest
    ports:
      - "8080:8080"
      - "50000:50000"
    secrets:
      - jenkins-user
      - jenkins-pass
    volumes:
      - jm:/var/jenkins_home
      - jmshare:/usr/share/jenkins/ref
	deploy:
      resources:
        reservations:
          memory: 500M
        limits:
          memory: 1000M	

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true

volumes:
  jm:
    driver: cloudstor:aws
    external: false
  jmshare:
    driver: cloudstor:aws
    external: false
