version: '3.1'

services:

  main:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - COMMAND_OPTIONS=-master http://${JENKINS_IP}:8080 -username ${MASTER_USER:-admin} -password ${MASTER_PASS:-admin} -labels 'test' -executors 5
    volumes:
      - jm:/workspace
    deploy:
      replicas: 1

volumes:
  jm:
    external: true
