version: '3.1'

services:

  main:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - COMMAND_OPTIONS=-master http://${JENKINS_IP}:8080 -username ${MASTER_USER:-admin} -password ${MASTER_PASS:-admin} -labels 'test' -executors 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    deploy:
      replicas: 1
